import { SpeakerSubmission } from "./types";

export const today = new Date().toISOString().split('T')[0];



export const placeholderPhoto = "https://ui-avatars.com/api/?name=Speaker&background=6366f1&color=ffffff&size=128";


export const sessions = [
    { title: "The ins and outs of production achitecture", speaker: "Yezur" },
    { title: "Integrating AI Agents to React Apps using Mastra", speaker: "Jackson Mwangi" },
    { title: "The Hidden Cost of Copy-Paste: Why Your App Should Depend on People, Not Just Code", speaker: "Kenneth Mathari" },
    { title: "Evals in AI Agents", speaker: "James" },
    { title: "React Native enigma with the new architecture(Greenfield and Browfield Mobile apps)", speaker: "Alvin Otuya" },
    { title: "Full-Stack AI: Building Production-Ready Applications with Next.js and Genkit", speaker: "Maina Wycliffe" },
    { title: "The Vibe Coder's Playbook: How Rules and MCPs Made My AI Development Actually Work", speaker: "Victor Mwenda" },
    { title: "GraphQL with Apollo: Data fetching with precision", speaker: "Roseland Andisi Ambuku" },
    { title: "Breaking Down the Frontend, Holding It Together: Microfrontends in a Monorepo", speaker: "Titus" },
    { title: "Component and E2E Testing with cypress", speaker: "Albina Nyawira Muturi" },
    { title: "Design Thinking: From Pull Request to Persona", speaker: "Zawadi Wanjala" },
    { title: "GitHub Spec Kit - Vibe code high-quality software faster.", speaker: "Mark Aloo" },
    { title: "Expo and Better Auth: Auth that doesn't suck", speaker: "Timothy Mugo" },
    { title: "Building agents with AI SDK", speaker: "Felix Jumason" },
    { title: "INSTRUMENTATION WITH OPENTELEMETRY ON NEXT JS  APPLICATIONS", speaker: "Daniel Gitari" },
  ];



export const speakerSubmissions: SpeakerSubmission[] = [
      {
        id: "3",
        email: "mathari580@gmail.com",
        fullName: "Kenneth Mathari",
        titleRole: "Snr Mobile Developer",
        linkedinProfile: "https://www.linkedin.com/in/kenneth-mathari/",
        socialMediaLinks: "https://github.com/KennethMathari",
        sessionType: "FS",
        sessionRoom: "FB1-3",
        sessionTime: "11:55-12:25",
        sessionDate: today,
        speakerBio: "",
        profilePhoto: placeholderPhoto,
        sessionTitle: "The Hidden Cost of Copy-Paste: Why Your App Should Depend on People, Not Just Code",

      },
      {
        id: "4",
        email: "jmskanyiri@gmail.com",
        fullName: "James",
        titleRole: "AI Engineer",
        linkedinProfile: "https://www.linkedin.com/in/james-kanyiri-b48b6b1a7/",
        socialMediaLinks: "https://github.com/jameskanyiri?tab=repositories",
        sessionType: "LS",
        sessionRoom: "LB1-2",
        sessionTime: "11:35 - 11:50",
        sessionDate: today,
        speakerBio: "",
        profilePhoto: placeholderPhoto,
        sessionTitle: "Evals in AI Agents",

      },
      {
        id: "5",
        email: "otuyaalvin@gmail.com",
        fullName: "Alvin Otuya",
        titleRole: "Senior Mobile Engineer",
        linkedinProfile: "https://www.linkedin.com/in/alvin-otuya-3744b7257?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
        socialMediaLinks: "x.com/alvinotuya",
        sessionType: "FS",
        sessionRoom: "FB1-2",
        sessionTime: "11:00 - 11:30",
        sessionDate: today,
        speakerBio: "",
        profilePhoto: placeholderPhoto,
        sessionTitle: "React Native enigma with the new architecture(Greenfield and Browfield Mobile apps)",

      },
      {
        id: "6",
        email: "wmmaina7@gmail.com",
        fullName: "Maina Wycliffe",
        titleRole: "Technical Solutions Architect (Unstacked Labs)",
        linkedinProfile: "https://www.linkedin.com/in/mainawycliffe/",
        socialMediaLinks: "https://allthingstypescript.dev/\nhttps://github.com/mainawycliffe/",
        sessionType: "FS",
        sessionRoom: "FB2-2",
        sessionTime: "11:00 - 11:30",
        sessionDate: today,
        speakerBio: "",
        profilePhoto: placeholderPhoto,
        sessionTitle: "Full-Stack AI: Building Production-Ready Applications with Next.js and Genkit",

      },
      {
        id: "7",
        email: "kiambi15@gmail.com",
        fullName: "Victor Mwenda",
        titleRole: "Senior Software Engineer",
        linkedinProfile: "https://www.linkedin.com/in/victor-mwenda/",
        socialMediaLinks: "https://www.victormwenda.com",
        sessionType: "FS",
        sessionRoom: "FB2-1",
        sessionTime: "10:05 - 10:35",
        sessionDate: today,
        speakerBio: "",
        profilePhoto: placeholderPhoto,
        sessionTitle: "The Vibe Coder's Playbook: How Rules and MCPs Made My AI Development Actually Work",

      },
      {
        id: "8",
        email: "roselandambuku@gmail.com",
        fullName: "Roseland Andisi Ambuku",
        titleRole: "Software Engineer",
        linkedinProfile: "https://www.linkedin.com/in/roseland-ambuku/",
        socialMediaLinks: "https://github.com/andisiambuku",
        sessionType: "LS",
        sessionRoom: "LB1-4",
        sessionTime: "15:05 - 15:20",
        sessionDate: today,
        speakerBio: "",
        profilePhoto: placeholderPhoto,
        sessionTitle: "GraphQL with Apollo: Data fetching with precision",

      },
      {
        id: "9",
        email: "titusgik@gmail.com",
        fullName: "Titus",
        titleRole: "“Breaking Down the Frontend, Holding It Together: Microfrontends in a Monorepo”",
        linkedinProfile: "https://www.linkedin.com/in/titus-thumbi-103882190/",
        socialMediaLinks: "https://www.linkedin.com/in/titus-thumbi-103882190/",
        sessionType: "LS",
        sessionRoom: "LB1-3",
        sessionTime: "12:30 - 12:45",
        sessionDate: today,
        speakerBio: "",
        profilePhoto: placeholderPhoto,
        sessionTitle: "Breaking Down the Frontend, Holding It Together: Microfrontends in a Monorepo",

      },
      {
        id: "10",
        email: "albinamuturi@gmail.com",
        fullName: "Albina Nyawira Muturi",
        titleRole: "Senior Software Engineer",
        linkedinProfile: "https://www.linkedin.com/in/nyawira-muturi/",
        socialMediaLinks: "https://dame-techie.hashnode.dev/",
        sessionType: "FS",
        sessionRoom: "FB2-4",
        sessionTime: "14:30 - 15:00",
        sessionDate: today,
        speakerBio: "",
        profilePhoto: placeholderPhoto,
        sessionTitle: "React Design Patterns",

      },
      {
        id: "11",
        email: "ateyasamson@gmail.com",
        fullName: "Samson Ateya",
        titleRole: "Cloud Engineer",
        linkedinProfile: "https://www.linkedin.com/in/sam-ateya?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        socialMediaLinks: "https://github.com/ateyasam85",
        sessionType: "LS",
        sessionRoom: "LB2-2",
        sessionTime: "11:35 - 11:50",
        sessionDate: today,
        speakerBio: "",
        profilePhoto: placeholderPhoto,
        sessionTitle: "Cloud computing AWS",

      },
      {
        id: "12",
        email: "g.zawadi.w@gmail.com",
        fullName: "Zawadi Wanjala",
        titleRole: "Technical Product Manager",
        linkedinProfile: "https://www.linkedin.com/in/grace-zawadi/",
        socialMediaLinks: "https://github.com/3N61N33R, https://x.com/zawadi_g_",
        sessionType: "FS",
        sessionRoom: "FB2-3",
        sessionTime: "11:55 - 12:25",
        sessionDate: today,
        speakerBio: "",
        profilePhoto: placeholderPhoto,
        sessionTitle: "Design Thinking: From Pull Request to Persona",

      },
      {
        id: "13",
        email: "mbenjerminne@gmail.com",
        fullName: "Mark Aloo",
        titleRole: "Software Engineer - Safaricom PLC",
        linkedinProfile: "https://www.linkedin.com/in/thecodeinfluencer/",
        socialMediaLinks: "https://thecodeinfluencer.dev/",
        sessionType: "LS",
        sessionRoom: "LB1-5",
        sessionTime: "10:00 - 10:35",
        sessionDate: today,
        speakerBio: "",
        profilePhoto: placeholderPhoto,
        sessionTitle: "Software Engineer - Safaricom PLC",

      },
      {
        id: "14",
        email: "timomugo01@gmail.com",
        fullName: "Timothy Mugo",
        titleRole: "Software Engineer",
        linkedinProfile: "https://www.linkedin.com/in/timothygachengo/",
        socialMediaLinks: "https://github.com/timothygachengo",
        sessionType: "LS",
        sessionRoom: "LB1-1",
        sessionTime: "10:40 - 10:55",
        sessionDate: today,
        speakerBio: "",
        profilePhoto: placeholderPhoto,
        sessionTitle: "Expo and Better Auth: Auth that doesn't suck",

      },
      {
        id: "15",
        email: "felixkent360@gmail.com",
        fullName: "Felix Jumason",
        titleRole: "Noc",
        linkedinProfile: "https://www.linkedin.com/in/felix-jumason-9b209a243/",
        socialMediaLinks: "https://twitter.com/blackie_360",
        sessionType: "LS",
        sessionRoom: "LB1-3",
        sessionTime: "12:30 - 12:45",
        sessionDate: today,
        speakerBio: "",
        profilePhoto: placeholderPhoto,
        sessionTitle: "Building agents with AI SDK",

      },
      {
        id: "16",
        email: "gitarimaina254@gmail.com",
        fullName: "Daniel Gitari",
        titleRole: "DEVOPS ENGINEER",
        linkedinProfile: "https://www.linkedin.com/in/daniel-maina-gitari-464396177/",
        socialMediaLinks: "https://www.linkedin.com/in/daniel-maina-gitari-464396177/",
        sessionType: "LS",
        sessionRoom: "LB2-4",
        sessionTime: "15:05 - 15:20",
        sessionDate: today,
        speakerBio: "",
        profilePhoto: placeholderPhoto,
        sessionTitle: "INSTRUMENTATION WITH OTENTELEMETRY ON NEXT JS  APPLICATIONS",

      },
      {
        id: "17",
        email: "smurgoh@gmail.com",
        fullName: "Simon Njeru",
        titleRole: "Bitcoin Dev",
        linkedinProfile: "",
        socialMediaLinks: "",
        sessionType: "LS",
        sessionRoom: "LB2-3",
        sessionTime: "12:30 - 12:45",
        sessionDate: today,
        speakerBio: "",
        profilePhoto: placeholderPhoto,
        sessionTitle: "Building a career in Bitcoin Open Source Development",

      },
    ];